class CountriesSelect
   def countries
   [
        { name: "Australia", code: "61", CountryCode: "AU" },
        { name: "Argentina", code: "54", CountryCode: "AR" },
        { name: "Afghanistan", code: "93", CountryCode: "AF" },
        { name: "Albania", code: "355", CountryCode: "AL" },
        { name: "Algeria", code: "213", CountryCode: "DZ" },
        { name: "American Samoa", code: "1684", CountryCode: "AS" },
        { name: "Andorra", code: "376", CountryCode: "AD" },
        { name: "Angola", code: "244", CountryCode: "AO" },
        { name: "Anguilla", code: "1264", CountryCode: "AI" },
        { name: "Antarctica", code: "672", CountryCode: "AQ" },
        { name: "Antigua and Barbuda", code: "1268", CountryCode: "AG" },
        { name: "Armenia", code: "374", CountryCode: "AM" },
        { name: "Aruba", code: "297", CountryCode: "AW" },
        { name: "Austria", code: "43", CountryCode: "AT" },
        { name: "Azerbaijan", code: "994", CountryCode: "AZ" },
        { name: "Bahrain", code: "973", CountryCode: "BH" },
      
        { name: "Bahamas", code: "1242", CountryCode: "BS" },
        { name: "Bangladesh", code: "880", CountryCode: "BD" },
        { name: "Barbados", code: "1246", CountryCode: "BB" },
        { name: "Belarus", code: "375", CountryCode: "BY" },
        { name: "Belgium", code: "32", CountryCode: "BE" },
        { name: "Belize", code: "501", CountryCode: "BZ" },
        { name: "Benin", code: "229", CountryCode: "BJ" },
        { name: "Bermuda", code: "1441", CountryCode: "BM" },
        { name: "Bhutan", code: "975", CountryCode: "BT" },
        { name: "Bolivia", code: "591", CountryCode: "BO" },
        { name: "Bosnia and Herzegovina", code: "387", CountryCode: "BA" },
        { name: "Botswana", code: "267", CountryCode: "BW" },
        { name: "Brazil", code: "55", CountryCode: "BR" },
        { name: "British Indian Ocean Territory", code: "246", CountryCode: "IO" },
        { name: "British Virgin Islands", code: "1284", CountryCode: "VG" },
        { name: "Brunei", code: "673", CountryCode: "BN" },
        { name: "Bulgaria", code: "359", CountryCode: "BG" },
        { name: "Burkina Faso", code: "226", CountryCode: "BF" },
        { name: "Burundi", code: "257", CountryCode: "BI" },
        { name: "Cambodia", code: "855", CountryCode: "KH" },
        { name: "Cameroon", code: "237", CountryCode: "CM" },
        { name: "Canada", code: "1", CountryCode: "CA" },
      
        { name: "Cape Verde", code: "238", CountryCode: "CV" },
        { name: "Cayman Islands", code: "1345", CountryCode: "KY" },
        { name: "Central African Republic", code: "236", CountryCode: "CF" },
        { name: "Chad", code: "235", CountryCode: "TD" },
        { name: "Chile", code: "56", CountryCode: "CL" },
        { name: "China", code: "86", CountryCode: "CN" },
      
        { name: "Christmas Island", code: "61", CountryCode: "CX" },
        { name: "Cocos Islands", code: "61", CountryCode: "CC" },
        { name: "Colombia", code: "57", CountryCode: "CO" },
        { name: "Comoros", code: "269", CountryCode: "KM" },
        { name: "Cook Islands", code: "682", CountryCode: "CK" },
        { name: "Costa Rica", code: "506", CountryCode: "CR" },
        { name: "Croatia", code: "385", CountryCode: "HR" },
        { name: "Cuba", code: "53", CountryCode: "CU" },
        { name: "Curacao", code: "599", CountryCode: "CW" },
        { name: "Cyprus", code: "357", CountryCode: "CY" },
        { name: "Czech Republic", code: "420", CountryCode: "CZ" },
        { name: "Democratic Republic of the Congo", code: "243", CountryCode: "CD" },
        { name: "Denmark", code: "45", CountryCode: "DK" },
        { name: "Djibouti", code: "253", CountryCode: "DJ" },
        { name: "Dominica", code: "1767", CountryCode: "DM" },
        { name: "Dominican Republic", code: "1809", CountryCode: "DO" },
        { name: "East Timor", code: "670", CountryCode: "TL" },
        { name: "Ecuador", code: "593", CountryCode: "EC" },
        { name: "Egypt", code: "20", CountryCode: "EG" },
        { name: "El Salvador", code: "503", CountryCode: "SV" },
        { name: "Equatorial Guinea", code: "240", CountryCode: "GQ" },
        { name: "Eritrea", code: "291", CountryCode: "ER" },
        { name: "Estonia", code: "372", CountryCode: "EE" },
        { name: "Ethiopia", code: "251", CountryCode: "ET" },
        { name: "Falkland Islands", code: "500", CountryCode: "FK" },
        { name: "Faroe Islands", code: "298", CountryCode: "FO" },
        { name: "Fiji", code: "679", CountryCode: "FJ" },
        { name: "Finland", code: "358", CountryCode: "FI" },
        { name: "France", code: "33", CountryCode: "FR" },
      
        { name: "French Polynesia", code: "689", CountryCode: "PF" },
        { name: "Gabon", code: "241", CountryCode: "GA" },
        { name: "Gambia", code: "220", CountryCode: "GM" },
      
        { name: "Georgia", code: "995", CountryCode: "GE" },
        { name: "Germany", code: "49", CountryCode: "DE" },
      
        { name: "Ghana", code: "233", CountryCode: "GH" },
        { name: "Gibraltar", code: "350", CountryCode: "GI" },
        { name: "Greece", code: "30", CountryCode: "GR" },
        { name: "Greenland", code: "299", CountryCode: "GL" },
        { name: "Grenada", code: "1473", CountryCode: "GD" },
        { name: "Guam", code: "1671", CountryCode: "GU" },
        { name: "Guatemala", code: "502", CountryCode: "GT" },
        { name: "Guernsey", code: "441481", CountryCode: "GG" },
        { name: "Guinea", code: "224", CountryCode: "GN" },
        { name: "GuineaBissau", code: "245", CountryCode: "GW" },
        { name: "Guyana", code: "592", CountryCode: "GY" },
        { name: "Haiti", code: "509", CountryCode: "HT" },
        { name: "Honduras", code: "504", CountryCode: "HN" },
        { name: "Hong Kong", code: "852", CountryCode: "HK" },
        { name: "Hungary", code: "36", CountryCode: "HU" },
        { name: "Iceland", code: "354", CountryCode: "IS" },
        { name: "India", code: "91", CountryCode: "IN" },
        { name: "Indonesia", code: "62", CountryCode: "ID" },
        { name: "Iran", code: "98", CountryCode: "IR" },
        { name: "Iraq", code: "964", CountryCode: "IQ" },
        { name: "Ireland", code: "353", CountryCode: "IE" },
        { name: "Isle of Man", code: "441624", CountryCode: "IM" },
        { name: "Israel", code: "972", CountryCode: "IL" },
        { name: "Italy", code: "39", CountryCode: "IT" },
      
        { name: "Ivory Coast", code: "225", CountryCode: "CI" },
        { name: "Jamaica", code: "1876", CountryCode: "JM" },
        { name: "Japan", code: "81", CountryCode: "JP" },
        { name: "Jersey", code: "441534", CountryCode: "JE" },
        { name: "Jordan", code: "962", CountryCode: "JO" },
        { name: "Kazakhstan", code: "7", CountryCode: "KZ" },
        { name: "Kenya", code: "254", CountryCode: "KE" },
        { name: "Kiribati", code: "686", CountryCode: "KI" },
        { name: "Kosovo", code: "383", CountryCode: "XK" },
        { name: "Kuwait", code: "965", CountryCode: "KW" },
        { name: "Kyrgyzstan", code: "996", CountryCode: "KG" },
        { name: "Laos", code: "856", CountryCode: "LA" },
        { name: "Latvia", code: "371", CountryCode: "LV" },
        { name: "Lebanon", code: "961", CountryCode: "LB" },
        { name: "Lesotho", code: "266", CountryCode: "LS" },
        { name: "Liberia", code: "231", CountryCode: "LR" },
        { name: "Libya", code: "218", CountryCode: "LY" },
        { name: "Liechtenstein", code: "423", CountryCode: "LI" },
        { name: "Lithuania", code: "370", CountryCode: "LT" },
        { name: "Luxembourg", code: "352", CountryCode: "LU" },
        { name: "Macau", code: "853", CountryCode: "MO" },
        { name: "Macedonia", code: "389", CountryCode: "MK" },
        { name: "Madagascar", code: "261", CountryCode: "MG" },
        { name: "Malawi", code: "265", CountryCode: "MW" },
        { name: "Malaysia", code: "60", CountryCode: "MY" },
        { name: "Maldives", code: "960", CountryCode: "MV" },
        { name: "Mali", code: "223", CountryCode: "ML" },
        { name: "Malta", code: "356", CountryCode: "MT" },
        { name: "Marshall Islands", code: "692", CountryCode: "MH" },
        { name: "Mauritania", code: "222", CountryCode: "MR" },
        { name: "Mauritius", code: "230", CountryCode: "MU" },
        { name: "Mayotte", code: "262", CountryCode: "YT" },
        { name: "Mexico", code: "52", CountryCode: "MX" },
        { name: "Micronesia", code: "691", CountryCode: "FM" },
        { name: "Moldova", code: "373", CountryCode: "MD" },
        { name: "Monaco", code: "377", CountryCode: "MC" },
        { name: "Mongolia", code: "976", CountryCode: "MN" },
        { name: "Montenegro", code: "382", CountryCode: "ME" },
        { name: "Montserrat", code: "1664", CountryCode: "MS" },
        { name: "Morocco", code: "212", CountryCode: "MA" },
        { name: "Mozambique", code: "258", CountryCode: "MZ" },
        { name: "Myanmar", code: "95", CountryCode: "MM" },
        { name: "Namibia", code: "264", CountryCode: "NA" },
        { name: "Nauru", code: "674", CountryCode: "NR" },
        { name: "Nepal", code: "977", CountryCode: "NP" },
        { name: "Netherlands", code: "31", CountryCode: "NL" },
        { name: "Netherlands Antilles", code: "599", CountryCode: "AN" },
        { name: "New Caledonia", code: "687", CountryCode: "NC" },
        { name: "New Zealand", code: "64", CountryCode: "NZ" },
        { name: "Nicaragua", code: "505", CountryCode: "NI" },
        { name: "Niger", code: "227", CountryCode: "NE" },
        { name: "Nigeria", code: "234", CountryCode: "NG" },
        { name: "Niue", code: "683", CountryCode: "NU" },
        { name: "North Korea", code: "850", CountryCode: "KP" },
        { name: "Northern Mariana Islands", code: "1670", CountryCode: "MP" },
        { name: "Norway", code: "47", CountryCode: "NO" },
        { name: "Oman", code: "968", CountryCode: "OM" },
        { name: "Pakistan", code: "92", CountryCode: "PK" },
        { name: "Palau", code: "680", CountryCode: "PW" },
        { name: "Palestine", code: "970", CountryCode: "PS" },
        { name: "Panama", code: "507", CountryCode: "PA" },
        { name: "Papua New Guinea", code: "675", CountryCode: "PG" },
        { name: "Paraguay", code: "595", CountryCode: "PY" },
        { name: "Peru", code: "51", CountryCode: "PE" },
        { name: "Philippines", code: "63", CountryCode: "PH" },
        { name: "Pitcairn", code: "64", CountryCode: "PN" },
        { name: "Poland", code: "48", CountryCode: "PL" },
        { name: "Portugal", code: "351", CountryCode: "PT" },
        { name: "Puerto Rico", code: "1", CountryCode: "PR" },
        { name: "Qatar", code: "974", CountryCode: "QA" },
        { name: "Republic of the Congo", code: "242", CountryCode: "CG" },
        { name: "Reunion", code: "262", CountryCode: "RE" },
        { name: "Romania", code: "40", CountryCode: "RO" },
        { name: "Russia", code: "7", CountryCode: "RU" },
        { name: "Rwanda", code: "250", CountryCode: "RW" },
        { name: "Saint Barthelemy", code: "590", CountryCode: "BL" },
        { name: "Saint Helena", code: "290", CountryCode: "SH" },
        { name: "Saint Kitts and Nevis", code: "1869", CountryCode: "KN" },
        { name: "Saint Lucia", code: "1758", CountryCode: "LC" },
        { name: "Saint Martin", code: "590", CountryCode: "MF" },
        { name: "Saint Pierre and Miquelon", code: "508", CountryCode: "PM" },
        {
          name: "Saint Vincent and the Grenadines",
          code: "1784",
          CountryCode: "VC",
        },
        { name: "Samoa", code: "685", CountryCode: "WS" },
        { name: "San Marino", code: "378", CountryCode: "SM" },
        { name: "Sao Tome and Principe", code: "239", CountryCode: "ST" },
        { name: "Saudi Arabia", code: "966", CountryCode: "SA" },
        { name: "Senegal", code: "221", CountryCode: "SN" },
        { name: "Serbia", code: "381", CountryCode: "RS" },
        { name: "Seychelles", code: "248", CountryCode: "SC" },
        { name: "Sierra Leone", code: "232", CountryCode: "SL" },
        { name: "Singapore", code: "65", CountryCode: "SG" },
        { name: "Sint Maarten", code: "1721", CountryCode: "SX" },
        { name: "Slovakia", code: "421", CountryCode: "SK" },
        { name: "Slovenia", code: "386", CountryCode: "SI" },
        { name: "Solomon Islands", code: "677", CountryCode: "SB" },
        { name: "Somalia", code: "252", CountryCode: "SO" },
        { name: "South Africa", code: "27", CountryCode: "ZA" },
        { name: "South Korea", code: "82", CountryCode: "KR" },
        { name: "South Sudan", code: "211", CountryCode: "SS" },
        { name: "Spain", code: "34", CountryCode: "ES" },
        { name: "Sri Lanka", code: "94", CountryCode: "LK" },
        { name: "Sudan", code: "249", CountryCode: "SD" },
        { name: "Suriname", code: "597", CountryCode: "SR" },
        { name: "Svalbard and Jan Mayen", code: "47", CountryCode: "SJ" },
        { name: "Swaziland", code: "268", CountryCode: "SZ" },
        { name: "Sweden", code: "46", CountryCode: "SE" },
        { name: "Switzerland", code: "41", CountryCode: "CH" },
        { name: "Syria", code: "963", CountryCode: "SY" },
        { name: "Taiwan", code: "886", CountryCode: "TW" },
        { name: "Tajikistan", code: "992", CountryCode: "TJ" },
        { name: "Tanzania", code: "255", CountryCode: "TZ" },
        { name: "Thailand", code: "66", CountryCode: "TH" },
        { name: "Togo", code: "228", CountryCode: "TG" },
        { name: "Tokelau", code: "690", CountryCode: "TK" },
        { name: "Tonga", code: "676", CountryCode: "TO" },
        { name: "Trinidad and Tobago", code: "1868", CountryCode: "TT" },
        { name: "Tunisia", code: "216", CountryCode: "TN" },
        { name: "Turkey", code: "90", CountryCode: "TR" },
        { name: "Turkmenistan", code: "993", CountryCode: "TM" },
        { name: "Turks and Caicos Islands", code: "1649", CountryCode: "TC" },
        { name: "Tuvalu", code: "688", CountryCode: "TV" },
        { name: "U.S. Virgin Islands", code: "1340", CountryCode: "VI" },
        { name: "Uganda", code: "256", CountryCode: "UG" },
        { name: "Ukraine", code: "380", CountryCode: "UA" },
      
        { name: "United Arab Emirates", code: "971", CountryCode: "AE" },
        { name: "United Kingdom", code: "44", CountryCode: "GB" },
        { name: "United States", code: "1", CountryCode: "US" },
        { name: "Uruguay", code: "598", CountryCode: "UY" },
        { name: "Uzbekistan", code: "998", CountryCode: "UZ" },
        { name: "Vanuatu", code: "678", CountryCode: "VU" },
        { name: "Vatican", code: "379", CountryCode: "VA" },
        { name: "Venezuela", code: "58", CountryCode: "VE" },
        { name: "Vietnam", code: "84", CountryCode: "VN" },
        { name: "Wallis and Futuna", code: "681", CountryCode: "WF" },
        { name: "Western Sahara", code: "212", CountryCode: "EH" },
        { name: "Yemen", code: "967", CountryCode: "YE" },
        { name: "Zambia", code: "260", CountryCode: "ZM" },
        { name: "Zimbabwe", code: "263", CountryCode: "ZW" },
      ]
   end
end